name: 🐞 Bug Report
description: Report a bug if something isn't working as expected in WooCommerce E2E Tests Boilerplate.
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for contributing!

        Please provide us with the information requested in this bug report. 
        Without these details, we won't be able to fully evaluate this issue. 
        Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

        Make sure to look through the [existing `bug` issues](https://github.com/woocommerce/woocommerce-e2e-boilerplate/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see whether your bug has already been submitted.
        Feel free to contribute to any existing issues.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting the issue.
      options:
        - label: I have carried out troubleshooting steps and I believe I have found a bug.
        - label: I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is and what actually happens. Please be as descriptive as possible.
        Please also include any error logs or output.
        If applicable you can attach screenshot(s) or recording(s) directly by dragging & dropping.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: WordPress Environment
      description: |
        If applicable you may wish to share the [WooCommerce System Status Report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) of your e2e test environment to help us evaluate the issue. 
      placeholder: |
        The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
        Please select “Get system report”, then “Copy for support”, and then paste it here.
  - type: checkboxes
    id: isolating
    attributes:
      label: Isolating the problem
      description: |
        Please try testing your e2e test environment for theme and plugins conflict. 
        To do that deactivate all plugins except for WooCommerce and switch to a default WordPress theme or [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again. 
        If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. 
        You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
      options:
        - label: I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
        - label: This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
        - label: I can reproduce this bug consistently using the steps above.